version: "3.1"

services:
  api:
    build: .
    ports:
      - 1323:1323
    environment:
      DATA_SOURCE_NAME: root:root@tcp(db:3306)/sample
      PORT: :1323
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample
    volumes:
      - ./migration:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
